name: Test Web

on:
  - push
  - pull_request

jobs:
  test-components:
    runs-on: ubuntu-latest
    container: cypress/included:9.4.1
    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.7'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test:form
